---
- name: Install Docker Playbook
  hosts: all
  become: yes
  tasks:
    - name: Check distro
      command: lsb_release -is
      register: distro

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/{{ distro.stdout | lower }}/gpg | apt-key add -
      when: distro.stdout in ["Ubuntu", "Debian"]

    - name: Set up stable repo
      command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/{{ distro.stdout | lower }} $(lsb_release -cs) stable"
      when: distro.stdout in ["Ubuntu", "Debian"]

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version installed: {{ docker_version.stdout }}"
